require 'rubygems'
require 'rspec'
require 'rspec/its'
require 'time'
require 'active_support/inflector'
require 'awsecrets'
require 'awspec/version'
require 'awspec/error'
require 'awspec/cli'
require 'awspec/stub'
require 'awspec/matcher'
require 'awspec/helper'
require 'awspec/ext'
require 'awspec/generator'
require 'awspec/toolbox'
require 'awspec/resource_reader'
require 'awspec/shared_context'

module Awspec
end
